project:
  type: website
  render:
    - "*.qmd"
    - "*.md"

website:
  title: "Tong Chen"
  site-url: "https://mariecurie.com"
  navbar:
    background: "#EEEEEE"
    left:
#      - href: blog/index.qmd
#        text: Blog
      - href: publications/index.qmd
        text: Publications
      - href: software/index.qmd
        text: Software
      - href: talks/index.qmd
        text: Seminars
#      - href: teaching/index.qmd
#        text: Teaching
      - href: about/index.qmd
        text: About
  page-footer:
    left: "Â© 2022-2026, Tong Chen"
    right:
      - icon: github
        href: https://github.com/T0ngChen
      - icon: bluesky
        href: https://bsky.app/profile/cttc101.bsky.social
    background: "#EEEEEE"

date-format: "D MMMM YYYY"

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true
    html-math-method: katex
    include-in-header:
      file: header.html

execute:
  freeze: auto
